// lib/content.ts
// Complete content data. Import from this file in all page components.
// NOTE: CMS integration (Sanity / Contentful) deferred to phase 2.

import type {
  Service, CaseStudy, TeamMember, ProcessPhase,
  Industry, Insight, HostingPackage, CompanyValue
} from './types'

export const services: Service[] = [
  {
    slug: 'website-development',
    name: 'Website Development',
    icon: 'website.svg',
    tagline: 'Custom CMS websites built for performance, security, and scale.',
    headline: 'Your website is your primary sales asset. It should perform like one.',
    subheadline: 'Custom-built websites planned, designed, and developed in-house by a senior team in North Sydney.',
    what: [ 'Custom CMS websites (WordPress, Laravel)', 'Responsive design, mobile-first', 'Interactive calculators, forms, and secure portals', 'Animation and micro-interaction layers', 'Penetration-tested builds as standard', 'SSL, 99.9% uptime SLA, scalable architecture' ],
    tech: ['WordPress', 'Laravel', 'PHP/MySQL', 'HTML5', 'CSS3', 'JavaScript ES6'],
    relatedWork: ['qantas-super', 'gme', 'sydney-packaging'],
    metaTitle: 'Website Development Sydney | Codex Digital',
    metaDescription: 'Custom website development in Sydney for enterprise and mid-market businesses. Built in-house. Mobile-first, penetration-tested, CMS-ready.',
  },
  {
    slug: 'design-ux-ui',
    name: 'Design & UX/UI',
    icon: 'design.svg',
    tagline: 'Interfaces engineered for usability and conversion.',
    headline: 'Design that works before it impresses.',
    subheadline: 'Interface design and UX strategy engineered for usability, accessibility, and conversion.',
    what: [ 'User journey mapping and wireframing', 'UI systems and component libraries', 'Interactive prototypes', 'Usability and accessibility audits', 'Conversion-focused design decisions' ],
    tech: ['Figma', 'Adobe XD', 'Prototyping', 'WCAG 2.1 AA'],
    relatedWork: ['qantas-super', 'nautilus-marine'],
    metaTitle: 'UX/UI Design Agency Sydney | Codex Digital',
    metaDescription: 'Interface design and UX strategy for enterprise digital products. Codex designs for usability, accessibility, and conversion.',
  },
  {
    slug: 'branding',
    name: 'Branding',
    icon: 'branding.svg',
    tagline: 'Brand systems built for consistency across every touchpoint.',
    headline: 'A brand system your whole organisation can use.',
    subheadline: 'From logo design to full brand identity — built for consistency, scalability, and market impact.',
    what: [ 'Logo design and brand mark development', 'Brand guidelines and identity systems', 'Print and digital collateral', 'Tone of voice and messaging frameworks', 'Brand rollout across web, app, and print' ],
    tech: ['Adobe Illustrator', 'Adobe InDesign', 'Figma'],
    relatedWork: ['energy-locals'],
    metaTitle: 'Branding Agency Sydney | Codex Digital',
    metaDescription: 'Brand strategy, identity systems, and logo design for Australian businesses. Codex builds brand systems that scale.',
  },
  {
    slug: 'mobile-apps',
    name: 'Mobile Apps',
    icon: 'mobile.svg',
    tagline: 'Native iOS and Android apps built for your platform and your users.',
    headline: 'Built for the platform. Designed for your users.',
    subheadline: 'Native iOS and Android apps with custom integrations — scoped to your business logic and built in-house.',
    what: [ 'Native iOS and Android applications', 'Dealer portals and broker tools', 'Insurance quote-and-bind platforms', 'ERP, CRM, and payment gateway integration', 'Azure Active Directory and SSO' ],
    tech: ['React Native', 'Swift', 'Kotlin', 'Laravel API', 'Azure AD', 'Westpac Merchant'],
    relatedWork: ['kawasaki-insurance'],
    metaTitle: 'Mobile App Development Sydney | Codex Digital',
    metaDescription: 'Custom iOS and Android app development in Sydney. Native builds with ERP and API integration. Delivered in-house by Codex Digital since 2015.',
  },
  {
    slug: 'custom-software',
    name: 'Custom Software',
    icon: 'software.svg',
    tagline: 'Tailored software when off-the-shelf does not fit your workflow.',
    headline: 'When off-the-shelf does not fit the workflow.',
    subheadline: 'Tailored software built to improve efficiency, reduce overhead, and scale with your business.',
    what: [ 'Intranet and internal platform development', 'ERP integration and workflow automation', 'SaaS tools and dealer dashboards', 'Quote-and-bind and insurance portals', 'Legacy system migration and API connections', 'Permission-controlled admin environments' ],
    tech: ['Laravel', 'PHP/MySQL', 'Azure AD', 'SSO', 'Westpac Merchant', 'REST API'],
    relatedWork: ['perfection-fresh', 'kawasaki-insurance', 'gme'],
    metaTitle: 'Custom Software Development Sydney | Codex Digital',
    metaDescription: 'Tailored software solutions for enterprise workflows. ERP integrations, SaaS platforms, dealer portals, and intranet systems built in-house.',
  },
  {
    slug: 'digital-campaigns',
    name: 'Digital Campaigns',
    icon: 'campaigns.svg',
    tagline: 'Strategy-led SEO, PPC, and campaign management. Measured by results.',
    headline: 'Strategy first. Results second. In that order.',
    subheadline: 'SEO, PPC, and campaign management delivered in-house — measured by outcomes, not activity.',
    what: [ 'SEO strategy and technical optimisation', 'PPC management (Google Ads, Meta)', 'Email marketing and automation', 'Campaign landing pages and microsites', 'Performance reporting — no vanity metrics' ],
    tech: ['Google Ads', 'Meta Ads', 'Google Analytics 4', 'Search Console', 'Klaviyo'],
    relatedWork: ['energy-locals', 'nautilus-marine'],
    metaTitle: 'Digital Campaign Agency Sydney | Codex Digital',
    metaDescription: 'Strategy-led digital campaigns including SEO, PPC, and email marketing. Codex manages campaigns in-house, from strategy to reporting.',
  },
  {
    slug: 'hosting-infrastructure',
    name: 'Hosting & Infrastructure',
    icon: 'hosting.svg',
    tagline: 'Managed enterprise hosting with 99.9% uptime SLA. Local support.',
    headline: 'Enterprise infrastructure. Local support.',
    subheadline: 'Managed hosting, server solutions, and infrastructure support delivered by the same team that built your site.',
    what: [ '99.9% uptime SLA', 'Daily automated backups', 'SSL certificates as standard', '24/7 server monitoring', 'Security hardening and penetration testing', 'Scalable plans for traffic growth' ],
    tech: ['cPanel', 'Linux', 'Nginx', 'Apache', 'Cloudflare', 'AWS'],
    relatedWork: ['qantas-super'],
    metaTitle: 'Managed Hosting Sydney | Codex Digital',
    metaDescription: 'Enterprise-grade managed website hosting in Sydney. 99.9% uptime SLA, daily backups, SSL, 24/7 monitoring. Scalable plans from $30/month.',
  },
]

export const caseStudies: CaseStudy[] = [
  {
    slug: 'qantas-super',
    client: 'Qantas Super',
    descriptor: 'A scalable platform for 32,000 members.',
    services: ['Website Development', 'Design & UX/UI', 'Hosting & Infrastructure'],
    industry: 'Financial Services',
    thumbnail: '/images/work/qantas-super.jpg',
    overview: 'Qantas Super required a complete digital rebuild to serve its 32,000 members and $7 billion in assets under management. The existing platform was underperforming on mobile and lacked the CMS flexibility required by the communications team.',
    challenge: 'Deliver a custom CMS website that meets enterprise security requirements, serves a large member base at scale, and is fully manageable by a non-technical marketing team.',
    role: 'Codex Digital led strategy, UX, design, custom WordPress development, and ongoing hosting and maintenance from inception to launch.',
    metrics: [
      { value: '31,500', label: 'users per month', sub: 'post-launch average' },
      { value: '50%',    label: 'engagement increase', sub: 'vs previous platform' },
      { value: '2×',     label: 'global award winner', sub: 'W3 + Davey Awards' },
    ],
    features: [
      'Custom WordPress CMS with member-facing content architecture',
      'Responsive, mobile-first design',
      'Secure member portal integration',
      'Content publishing workflow for marketing team',
      'Performance-optimised hosting on managed infrastructure',
    ],
    tech: ['WordPress', 'PHP/MySQL', 'HTML5', 'CSS3', 'JavaScript', 'cPanel'],
    awards: ['Gold W3 Award – Best Website in Financial Services 2018', 'Gold Davey Award – Best Website in Financial Services 2018'],
    metaTitle: 'Qantas Super | Codex Digital',
    metaDescription: 'Gold W3 and Davey Award-winning website for Qantas Super. A custom CMS platform serving 32,000 members and $7 billion AUM, built in-house by Codex Digital.',
  },
  {
    slug: 'sydney-packaging',
    client: 'Sydney Packaging',
    descriptor: 'From invisible to industry-leading online.',
    services: ['Website Development', 'Design & UX/UI'],
    industry: 'Manufacturing & Distribution',
    thumbnail: '/images/work/sydney-packaging.jpg',
    overview: 'Sydney Packaging needed a complete website rebuild to convert their dominant offline reputation into online lead generation. Their existing site was generating negligible digital enquiries.',
    challenge: 'Build a conversion-focused website that positions Sydney Packaging as the leading packaging supplier in the market and drives qualified enquiries.',
    role: 'Codex Digital delivered strategy, design, custom development, and SEO-optimised content architecture.',
    metrics: [
      { value: '870%', label: 'increase in enquiries', sub: 'year one post-launch' },
      { value: '100%', label: 'year-on-year revenue growth', sub: 'attributed to digital channel' },
    ],
    features: [
      'Custom product catalogue with enquiry workflows',
      'SEO-structured content architecture',
      'Mobile-first responsive design',
      'Lead capture and contact management',
    ],
    tech: ['WordPress', 'PHP/MySQL', 'HTML5', 'CSS3'],
    metaTitle: 'Sydney Packaging | Codex Digital',
    metaDescription: '870% increase in enquiries. Codex Digital rebuilt Sydney Packaging\'s website to convert offline brand strength into measurable digital lead generation.',
  },
  {
    slug: 'gme',
    client: 'GME',
    descriptor: 'A dealer ecosystem for a national hardware brand.',
    services: ['Website Development', 'Custom Software'],
    industry: 'Manufacturing & Distribution',
    thumbnail: '/images/work/gme.jpg',
    overview: 'GME required a public-facing website rebuild alongside a custom dealer portal to manage product registrations, warranty claims, and dealer logins across their national network.',
    challenge: 'Unify the public website and dealer portal into a single ecosystem that increases product registration and dealer engagement.',
    role: 'Codex Digital delivered the full-stack solution: public website redesign and a bespoke dealer portal with login, product registration, and reporting.',
    metrics: [
      { value: '308%', label: 'increase in product registrations' },
      { value: '401%', label: 'increase in dealer portal logins' },
    ],
    features: [
      'Custom WordPress website with product catalogue',
      'Dealer portal with authenticated login',
      'Product registration and warranty workflow',
      'Dealer reporting dashboard',
    ],
    tech: ['WordPress', 'Laravel', 'PHP/MySQL', 'REST API'],
    metaTitle: 'GME | Codex Digital',
    metaDescription: '308% increase in product registrations. 401% increase in dealer portal logins. Codex Digital built GME\'s website and custom dealer portal from the ground up.',
  },
  {
    slug: 'perfection-fresh',
    client: 'Perfection Fresh',
    descriptor: 'An intranet that connects a national fresh produce company.',
    services: ['Custom Software'],
    industry: 'Manufacturing & Distribution',
    thumbnail: '/images/work/perfection-fresh.jpg',
    overview: 'Perfection Fresh needed a company-wide intranet to connect distributed teams across its national operations, replacing fragmented email-based communication and manual workflows.',
    challenge: 'Design and build an intranet platform that improves internal communication, streamlines workflows, and is adopted across a non-technical workforce.',
    role: 'Codex Digital delivered the full intranet platform: architecture, design, development, and rollout support.',
    metrics: [
      { value: '20%', label: 'increase in internal workflow efficiency' },
    ],
    features: [
      'Company-wide intranet platform',
      'News and announcements module',
      'Document management and version control',
      'Staff directory and org chart',
      'Permission-controlled access by role',
    ],
    tech: ['Laravel', 'PHP/MySQL', 'Azure AD', 'SSO'],
    metaTitle: 'Perfection Fresh Intranet | Codex Digital',
    metaDescription: '20% increase in workflow efficiency. Codex Digital built a company-wide intranet platform for Perfection Fresh, connecting distributed teams across Australia.',
  },
  {
    slug: 'energy-locals',
    client: 'Energy Locals',
    descriptor: 'Brand and digital for a challenger energy retailer.',
    services: ['Branding', 'Website Development', 'Digital Campaigns'],
    industry: 'Energy & Utilities',
    thumbnail: '/images/work/energy-locals.jpg',
    overview: 'Energy Locals launched as a challenger brand in the competitive retail energy market. They needed a brand identity, digital presence, and customer acquisition platform built from the ground up.',
    challenge: 'Create a brand and digital ecosystem that differentiates Energy Locals from incumbent energy retailers and drives cost-effective customer sign-ups.',
    role: 'Codex Digital delivered brand strategy, identity design, website development, a custom sign-up platform, and ongoing digital campaign management.',
    metrics: [
      { value: '51%', label: 'increase in website traffic' },
      { value: '25%', label: 'increase in new customers', sub: 'attributed to digital campaigns' },
    ],
    features: [
      'Full brand identity system',
      'WordPress website',
      'Custom subscription sign-up platform with geo-targeting',
      'SEO and Google Ads campaign management',
    ],
    tech: ['WordPress', 'Laravel', 'PHP/MySQL', 'PayPal', 'Google Ads'],
    metaTitle: 'Energy Locals | Codex Digital',
    metaDescription: '51% traffic increase. 25% new customer growth. Codex Digital delivered brand identity, website, and campaign management for challenger energy retailer Energy Locals.',
  },
  {
    slug: 'nautilus-marine',
    client: 'Nautilus Marine',
    descriptor: '65% online growth for Australia\'s leading marine insurer.',
    services: ['Website Development', 'Digital Campaigns'],
    industry: 'Insurance & Broking',
    thumbnail: '/images/work/nautilus-marine.jpg',
    overview: 'Nautilus Marine is Australia\'s largest dedicated marine insurance provider. They engaged Codex to rebuild their digital presence and drive online policy growth.',
    challenge: 'Modernise an outdated web presence and deploy a results-driven digital campaign strategy to grow Nautilus Marine\'s online policy base.',
    role: 'Codex delivered the website rebuild, SEO strategy, and ongoing paid and organic campaign management.',
    metrics: [
      { value: '65%',    label: 'online growth', sub: 'year-on-year' },
      { value: '35,000', label: 'insured customers nationally' },
    ],
    features: [
      'Custom website with product pages per vessel type',
      'SEO architecture for competitive insurance keywords',
      'Google Ads and Meta campaign management',
      'Performance reporting dashboard',
    ],
    tech: ['WordPress', 'PHP', 'Google Analytics 4', 'Google Ads', 'Meta Ads'],
    metaTitle: 'Nautilus Marine | Codex Digital',
    metaDescription: '65% online growth. Codex Digital rebuilt Nautilus Marine\'s website and drove a sustained digital campaign strategy for Australia\'s largest dedicated marine insurer.',
  },
  {
    slug: 'kawasaki-insurance',
    client: 'Kawasaki Insurance',
    descriptor: 'A quote-and-bind portal for 278 dealerships.',
    services: ['Mobile Apps', 'Custom Software'],
    industry: 'Insurance & Broking',
    thumbnail: '/images/work/kawasaki-insurance.jpg',
    overview: 'Kawasaki required a custom insurance portal allowing its national dealer network to quote and bind motorcycle insurance policies at point of sale, connected to the Kawasaki Insurances underwriting system.',
    challenge: 'Build a secure, fast, mobile-ready portal that enables 278 dealerships to process insurance quotes and bind policies without manual intervention.',
    role: 'Codex Digital delivered the full portal: architecture, design, development, payment integration, and dealer onboarding.',
    metrics: [
      { value: '278',    label: 'dealerships on the platform' },
      { value: '32,000', label: 'motorcycles quoted' },
    ],
    features: [
      'Custom insurance quote-and-bind portal',
      'Dealer login and permission management',
      'Policy binding with payment integration (Westpac)',
      'Admin reporting environment',
      'Mobile-optimised interface for dealership floor use',
    ],
    tech: ['Laravel', 'PHP/MySQL', 'Westpac Merchant', 'Azure AD', 'SSO'],
    metaTitle: 'Kawasaki Insurance Portal | Codex Digital',
    metaDescription: 'Custom insurance quote-and-bind portal for 278 Kawasaki dealerships. 32,000 motorcycles quoted. Built in-house by Codex Digital.',
  },
]

export const team: TeamMember[] = [
  {
      name: 'Jason Toyer',
      role: 'Director',
      since: 2005,
      bio: 'Jason has been building digital products since 2005 and founded Codex Digital in 2015. He leads client strategy and ensures every engagement is set up for delivery success.',
      photo: '/images/team/jason-toyer.jpg',
      email: 'jason@codexdigital.com.au',
      linkedin: '#',
    },
    {
      name: 'Sam Pryor',
      role: 'Development Lead',
      since: 2000,
      bio: 'Sam leads all development at Codex and has been writing code professionally since 2000. He oversees architecture decisions and is hands-on across every project.',
      photo: '/images/team/sam-pryor.jpg',
      linkedin: '#',
    },
    {
      name: 'Nathan Dailo',
      role: 'Front End Developer',
      since: 2007,
      bio: 'Nathan has specialised in front end development since 2007, building interfaces that are as reliable as they are precise.',
      photo: '/images/team/nathan-dailo.jpg',
      linkedin: '#',
    },
    {
      name: 'Michael Collins',
      role: 'Creative Lead',
      since: 2008,
      bio: 'Michael leads design across all Codex projects. Since 2008 he has developed brand systems, UX frameworks, and digital interfaces for enterprise clients across Australia.',
      photo: '/images/team/michael-collins.jpg',
      linkedin: '#',
    },
  ]

export const processPhases: ProcessPhase[] = [
  {
    number: 1,
    name: 'Opportunity',
    leader: 'Both',
    description: 'We meet to understand your goals, constraints, audience, and technical context. This is a discovery conversation, not a sales pitch.',
    deliverable: 'Project scope summary and fit assessment',
  },
  {
    number: 2,
    name: 'Exploration',
    leader: 'Codex',
    description: 'We analyse your current digital position, review competitors, and define the strategy — sitemap, content architecture, and technical approach.',
    deliverable: 'Sitemap, brief, and project specification',
  },
  {
    number: 3,
    name: 'Design',
    leader: 'Codex',
    description: 'We design your product in Figma — from wireframes to full-fidelity UI. You review, give feedback, and approve before any code is written.',
    deliverable: 'Approved design system and all page designs in Figma',
  },
  {
    number: 4,
    name: 'Development',
    leader: 'Codex',
    description: 'We build the approved designs in code. Fortnightly check-ins keep you informed. A staging environment is available throughout development.',
    deliverable: 'Fully built, QA-tested site on staging',
  },
  {
    number: 5,
    name: 'Rollout & Launch',
    leader: 'Both',
    description: 'We conduct final checks, migrate content, configure DNS, and execute a controlled launch. We monitor closely in the 72 hours after go-live.',
    deliverable: 'Live site, launch confirmation, handover documentation',
  },
  {
    number: 6,
    name: 'Growth & Maintenance',
    leader: 'Codex',
    description: 'The relationship continues post-launch. We provide hosting, ongoing maintenance, performance monitoring, and iterative improvements.',
    deliverable: 'Monthly maintenance reports, on-call support, quarterly reviews',
  },
]

export const industries: Industry[] = [
  {
    slug: 'financial-services',
    name: 'Financial Services',
    headline: 'Award-winning digital for financial services.',
    subheadline: 'Gold W3 and Davey Award winners. Preferred provider to Steadfast Group (ASX: SDF).',
    body: 'Codex Digital has built custom digital products for some of Australia\'s most recognised financial services brands. We understand compliance-aware builds, member portals, and the need for enterprise-grade security across every project.',
    services: ['Website Development', 'Custom Software', 'Hosting & Infrastructure', 'Design & UX/UI'],
    relatedWork: ['qantas-super', 'nautilus-marine'],
    showAwardBlock: true,
    metaTitle: 'Financial Services Digital Agency | Codex Digital',
    metaDescription: 'Award-winning digital for financial services. Gold W3 and Davey Award winners. Preferred provider to Steadfast Group (ASX: SDF). Custom websites and portals.',
  },
  {
    slug: 'insurance-broking',
    name: 'Insurance & Broking',
    headline: 'Digital platforms built for the insurance sector.',
    subheadline: 'From broker portals to quote-and-bind systems — built to the security and performance standards the sector demands.',
    body: 'We have delivered custom insurance platforms for some of Australia\'s leading underwriters and broker networks. Our work in this sector spans quote-and-bind portals, broker tools, and public-facing policy management platforms.',
    services: ['Custom Software', 'Mobile Apps', 'Website Development'],
    relatedWork: ['kawasaki-insurance', 'nautilus-marine'],
    showAwardBlock: false,
    metaTitle: 'Insurance & Broking Digital Agency | Codex Digital',
    metaDescription: 'Custom digital platforms for insurance and broking businesses. Dealer portals, quote-and-bind systems, and broker tools built in-house by Codex Digital.',
  },
  {
    slug: 'energy-utilities',
    name: 'Energy & Utilities',
    headline: 'Digital for energy retailers that need to move fast.',
    subheadline: 'Brand, web, and acquisition platforms for challenger and established energy businesses.',
    body: 'We built Energy Locals\' brand identity, website, and sign-up platform from scratch — and managed their digital campaigns through their growth phase. We understand the acquisition model, the compliance requirements, and the competitive dynamics of the retail energy market.',
    services: ['Branding', 'Website Development', 'Digital Campaigns', 'Custom Software'],
    relatedWork: ['energy-locals'],
    showAwardBlock: false,
    metaTitle: 'Energy & Utilities Digital Agency | Codex Digital',
    metaDescription: 'Brand, website, and digital campaigns for energy retailers. Codex Digital built Energy Locals\' brand and platform from the ground up.',
  },
  {
    slug: 'manufacturing-distribution',
    name: 'Manufacturing & Distribution',
    headline: 'Digital infrastructure for manufacturers with national reach.',
    subheadline: 'Dealer portals, intranet platforms, and product catalogues built for scale.',
    body: 'We have built dealer portals, intranet systems, and product registration platforms for major Australian manufacturers. Our work in this sector integrates web, software, and internal tooling into a single coherent digital ecosystem.',
    services: ['Website Development', 'Custom Software', 'Design & UX/UI'],
    relatedWork: ['gme', 'perfection-fresh', 'sydney-packaging'],
    showAwardBlock: false,
    metaTitle: 'Manufacturing Digital Agency | Codex Digital',
    metaDescription: 'Dealer portals, intranet platforms, and product catalogues for Australian manufacturers. Built in-house by Codex Digital.',
  },
  {
    slug: 'saas-subscription',
    name: 'SaaS & Subscription Platforms',
    headline: 'Platforms built to scale.',
    subheadline: 'Subscription and SaaS platforms with the architecture to grow — custom-built, not templated.',
    body: 'We build sign-up flows, payment integrations, user dashboards, and admin environments for subscription businesses. Our platforms are built to handle growth — with payment gateway integration, geo-targeting, and scalable infrastructure from day one.',
    services: ['Custom Software', 'Website Development', 'Hosting & Infrastructure'],
    relatedWork: ['energy-locals', 'kawasaki-insurance'],
    showAwardBlock: false,
    metaTitle: 'SaaS Development Agency Australia | Codex Digital',
    metaDescription: 'Custom SaaS and subscription platform development. Sign-up flows, payment integrations, user dashboards, and scalable infrastructure. Codex Digital, North Sydney.',
  },
]

export const insights: Insight[] = [
  {
    slug: 'how-to-choose-a-web-development-agency-sydney',
    title: 'How to choose a web development agency in Sydney',
    category: 'Web Development',
    readTime: '6 min read',
    publishDate: '2025-03-15',
    excerpt: 'Not all digital agencies are equal. Here is what to look for when shortlisting a web development partner for your next project.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    content: '',
    metaTitle: 'How to Choose a Web Development Agency in Sydney | Codex Digital',
    metaDescription: 'A practical guide to shortlisting web development agencies in Sydney. What questions to ask, what to look for, and what to avoid.',
  },
  {
    slug: 'enterprise-website-redesign-checklist',
    title: 'Enterprise website redesign: a practical checklist',
    category: 'Web Development',
    readTime: '8 min read',
    publishDate: '2025-02-20',
    excerpt: 'A website redesign is a significant investment. This checklist covers what to plan for before briefing an agency.',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&q=80',
    content: '',
    metaTitle: 'Enterprise Website Redesign Checklist | Codex Digital',
    metaDescription: 'A practical checklist for planning an enterprise website redesign. From brief to launch — what to consider before you start.',
  },
  {
    slug: 'custom-software-vs-off-the-shelf',
    title: 'Custom software vs off-the-shelf: a decision framework',
    category: 'Software',
    readTime: '7 min read',
    publishDate: '2025-01-30',
    excerpt: 'When does it make sense to build custom software — and when should you buy? A framework for making the right call.',
        image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    content: '',
    metaTitle: 'Custom Software vs Off-the-Shelf | Codex Digital',
    metaDescription: 'A decision framework for choosing between custom software development and off-the-shelf solutions. From Codex Digital.',
  },
  {
    slug: 'what-to-include-in-a-web-development-brief',
    title: 'What to include in a web development brief',
    category: 'Strategy',
    readTime: '5 min read',
    publishDate: '2024-12-10',
    excerpt: 'A strong brief sets the project up for success. Here is what a good web development brief looks like.',
        image: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&q=80',
    content: '',
    metaTitle: 'What to Include in a Web Development Brief | Codex Digital',
    metaDescription: 'A practical guide to writing a web development brief that gets you the right outcome. What to include and why.',
  },
  {
    slug: 'why-in-house-delivery-matters',
    title: 'Why in-house delivery matters for complex digital projects',
    category: 'Strategy',
    readTime: '4 min read',
    publishDate: '2024-11-05',
    excerpt: 'Outsourcing and contractor models look attractive on paper. Here is why senior in-house delivery changes outcomes.',
        image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
    content: '',
    metaTitle: 'Why In-House Delivery Matters | Codex Digital',
    metaDescription: 'Why senior in-house digital delivery produces better outcomes than contractor or offshore models. From Codex Digital.',
  },
]

export const hostingPackages: HostingPackage[] = [
  {
    name: 'Startup',
    price: '$30/month',
    recommended: false,
    features: [
      '5GB storage',
      'SSL certificate',
      'Daily backups (7-day retention)',
      '99.9% uptime SLA',
      'Email support',
    ],
    ctaLabel: 'Talk to us',
  },
  {
    name: 'Professional',
    price: '$80/month',
    recommended: true,
    features: [
      '20GB storage',
      'SSL certificate',
      'Daily backups (30-day retention)',
      '99.9% uptime SLA',
      '24/7 monitoring',
      'Priority email + phone support',
      'Monthly performance report',
    ],
    ctaLabel: 'Talk to us',
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    recommended: false,
    features: [
      'Unlimited storage',
      'SSL certificate',
      'Daily backups (90-day retention)',
      '99.9% uptime SLA',
      '24/7 monitoring + escalation',
      'Dedicated account manager',
      'Penetration testing included',
      'Quarterly infrastructure review',
    ],
    ctaLabel: 'Contact us',
  },
]

export const companyValues: CompanyValue[] = [
  { name: 'Excellence', description: 'We do not ship work we would not put our name on.' },
  { name: 'Accountability', description: 'One team. One point of contact. No exceptions.' },
  { name: 'Teamwork', description: 'Senior practitioners collaborate across every discipline on every project.' },
  { name: 'Client-centred', description: 'The brief is the starting point. Outcomes are what we measure.' },
  { name: 'Integrity', description: 'We tell clients what they need to hear, not what they want to hear.' },
  { name: 'Leadership', description: 'We take ownership of the result � from the first meeting to the last maintenance report.' },
]

